# .github/workflows/release.yml
name: Auto Release

permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-release')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --coverage --watchAll=false

    - name: Build library
      run: npm run build:lib

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Determine version bump
      id: version_bump
      run: |
        if [[ "${{ github.event.head_commit.message }}" =~ \[major\] ]]; then
          echo "bump=major" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.head_commit.message }}" =~ \[minor\] ]]; then
          echo "bump=minor" >> $GITHUB_OUTPUT
        else
          echo "bump=patch" >> $GITHUB_OUTPUT
        fi

    - name: Bump version and create tag
      run: |
        npm version ${{ steps.version_bump.outputs.bump }} -m "Release %s [skip-release]"
        git push origin master --tags

    - name: Get new version
      id: package_version
      run: |
        echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package_version.outputs.version }}
        release_name: Release v${{ steps.package_version.outputs.version }}
        body: |
          Changes in this Release
          - Auto-generated release from commit: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
